version: '3.6'
services:
  nginx:
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./configs:/etc/nginx/vhost.d
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro

  acme:
    container_name: nginx-proxy-acme
    image: nginxproxy/acme-companion
    volumes:
      - acme:/etc/acme.sh
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=alexflores120@gmail.com