version: '3.6'
services:
  nginx:
    name: nginx-proxy
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - 443:443
    volumes:
      - ./configs:/etc/nginx/vhost.d
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
